# Generated by Django 3.1.5 on 2021-01-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='subject',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='content',
            field=models.TextField(default='', null=True),
        ),
    ]
